name: Lighthouse Audits

on:
  push:
    branches:
    - gh-pages

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.3.2
      with:
        url: 'https://teomrd.github.io/miropad/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
