name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  dry-versioning:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.dry-versioning.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version
        uses: anothrNick/github-tag-action@1.67.0
        id: dry-versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true
  build-and-deploy:
    runs-on: ubuntu-latest
    needs:
      - dry-versioning
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write
    env:
      NEW_VERSION: ${{needs.dry-versioning.outputs.new_tag}}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: ✌️ Set version environment variable
        shell: bash
        run: echo "NEW_VERSION=${{ env.NEW_VERSION }}" >> $GITHUB_ENV
      - run: make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  versioning:
    runs-on: ubuntu-22.04
    needs:
      - build-and-deploy
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.app-versioning.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: app-versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch