name: Audit MiroPad with Lighthouse 
on:
  push:
    branches:
      - lighthouse
jobs:
  build-and-audit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: make build
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @lhci/cli@0.14.x
      - run: lhci autorun
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}