name: On Pull Requests
on:
  push:
    branches:
      - deno
  pull_request:
    branches:
      - main
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: make checks
      - run: make build
