name: On Pull Requests
on:
  pull_request:
    branches:
      - main
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: make checks
      - run: make build
      - name: Lighthouse audits
        uses: ./.github/actions/lighthouse-audit
